############################
## HUGO MODULES
############################

imports:
  - path: github.com/HugoBlox/hugo-blox-builder/modules/blox-core
    mounts:
      - source: layouts
        target: layouts
  - path: github.com/HugoBlox/hugo-blox-builder/modules/blox-bootstrap/v5
  - path: github.com/HugoBlox/hugo-blox-builder/modules/blox-plugin-decap-cms
  - path: github.com/HugoBlox/hugo-blox-builder/modules/blox-plugin-netlify